### ISSUE TITLE
What version is EnrichR now?

### ISSUE THREAD

**Issue by levinhein** [MaayanLab/Enrichr-Viz-Appyter#10]
Hello. May I ask where to find the version of EnrichR Web? Is it also 3.1? I couldn't find this information in the website. I need it for proper in-text citation to include the software version. Thank you :)

**Comment by AviMaayan** [comment]
@levinhein we do not follow a release schedule so you should site the date when you used it.

**Comment by levinhein** [comment]
> @levinhein we do not follow a release schedule so you should cite the date when you used it.

Noted on this. Thanks for the advice and thank you for developing the web server. Very useful and convenient! Have a nice day!
